server:
  port: 8081
  servlet:
    context-path: /zl
  tomcat:
    uri-encoding: UTF-8
    max-connections: 20
    max-threads: 2
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jpa:
    generate-ddl: false
    show-sql: true
  datasource:
      url: jdbc:mysql://localhost:3306/storm?useSSL=false&amp;zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=UTF-8&amp;autoReconnect=true
      username: root
      password: 123456
      driver-class: com.mysql.jdbc.Driver
      initialSize: 30
      minIdle: 30
      maxActive: 100
zl:
  key:
    path: classpath:keys/
